version: '3'
services:
    #Nginx service
    nginx:
        build: ./nginx
        depends_on:
          - api
          - client
        ports:
          - "3050:80"
    #Postgres database
    postgres_db:
        image: "postgres:latest"
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #Redis database
    redis_db:
        image: "redis:latest"
    #API service
    api:
        build: ./server
        image: "parveshkaushik/complex_api"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
            - PGHOST=postgres_db
            - PGPORT=5432
            - PGUSER=postgres
            - PGPASSWORD=postgres_password
            - PGDATABASE=postgres
   # Worker service
    worker:
        build: ./worker
        image: "parveshkaushik/complex_worker"
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
    #Frontend service
    client:
        build: ./client
        image: "parveshkaushik/complex_client"